{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.name" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
